package ai.prism.boot;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.ObjectProvider;
import org.springframework.boot.context.event.ApplicationReadyEvent;
import org.springframework.boot.info.GitProperties;
import org.springframework.context.event.EventListener;
import org.springframework.stereotype.Component;

/**
 * Logs, once at startup, the git commit the running app was built from — so it is obvious
 * which build is live (especially inside a container). The commit comes from {@code git.properties}
 * generated by the git-commit-id plugin and surfaced as a {@link GitProperties} bean; if that file
 * is absent (e.g. a build with no {@code .git}), it logs {@code unknown} rather than failing.
 */
@Component
class BuildInfoLogger {

    private static final Logger log = LoggerFactory.getLogger(BuildInfoLogger.class);

    private final ObjectProvider<GitProperties> gitProperties;

    BuildInfoLogger(ObjectProvider<GitProperties> gitProperties) {
        this.gitProperties = gitProperties;
    }

    @EventListener(ApplicationReadyEvent.class)
    void logBuildInfo() {
        GitProperties git = gitProperties.getIfAvailable();
        if (git == null) {
            log.info("Build info: commit=unknown (no git.properties on the classpath)");
            return;
        }
        log.info("Build info: commit={} branch={} dirty={} builtAt={}",
                git.getShortCommitId(), git.getBranch(), git.get("dirty"), git.get("build.time"));
    }
}
